zuul:
  routes:
    movie-service:
      serviceId: movie-service
      path: /movie-service/**
      #url: http://localhost:8090/api/v1/
    login-service:
      path: /login-service/**
      #url: http://localhost:8070/api/v1/

movie-service:
  ribbon:
    listOfServers: localhost:8090

login-service:
  ribbon:
    listOfServers: localhost:8070

authentication:
  secret: "asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4"