server.port: 8080
zuul:
  routes:
    movie-service:
      path: /movie-service/**
      url: http://localhost:8090/api/v1/
    login-service:
      path: /login-service/**
      url: http://localhost:8070/api/v1/
authentication:
  secret: "asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4"
logging.level:
  root: warn
  com.rombusthere.codemotioncloudpath.proxyservice: debug