server.port: 8070
spring:
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
  jpa:
    open-in-view: false
security:
  allowed-users:
    - username: userino
      password: passwordina
logging.level:
  root: warn
  com.rhombusthere.codemotioncloudpath.loginservice: debug